import { PolicyLayout } from '@/components/PolicyLayout'

export const metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Salient AI Accounting Platform',
}

export default function TermsOfService() {
  return (
    <PolicyLayout title="Terms of Service">
      <p className="lead">
        Last updated: February 25, 2025
      </p>

      <h2>Introduction</h2>
      <p>
        Welcome to Salient, an AI-powered accounting platform operated by Himalayas X LLC (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;). These Terms of Service (&quot;Terms&quot;) govern your access to and use of our platform, including any associated mobile applications, websites, software, and services (collectively, the &quot;Service&quot;).
      </p>
      <p>
        By accessing or using our Service, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Service. Please read these Terms carefully before using our Service.
      </p>

      <h2>Service Description</h2>
      <p>
        Salient is an AI-powered accounting platform that provides various financial management tools and services, including but not limited to:
      </p>
      <ul>
        <li>AI-powered receipt scanning and processing</li>
        <li>Automated transaction categorization</li>
        <li>Financial insights and reporting</li>
        <li>Bank account connection and synchronization</li>
        <li>Tax calculation assistance</li>
        <li>Cash flow predictions and forecasting</li>
        <li>Vendor payment automation</li>
      </ul>
      <p>
        The specific features and services available to you depend on the subscription plan you select. We reserve the right to modify, suspend, or discontinue any aspect of our Service at any time.
      </p>

      <h2>Account Registration and Security</h2>
      <p>
        To access certain features of our Service, you must create an account. When registering for an account, you agree to provide accurate, current, and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
      </p>
      <p>
        You agree to:
      </p>
      <ul>
        <li>Create a strong password and keep it confidential</li>
        <li>Restrict access to your account and devices</li>
        <li>Notify us immediately of any unauthorized use of your account</li>
        <li>Ensure that you log out from your account at the end of each session</li>
      </ul>
      <p>
        We reserve the right to disable any user account if, in our opinion, you have violated any provision of these Terms.
      </p>

      <h2>User Responsibilities</h2>
      <p>
        When using our Service, you agree to:
      </p>
      <ul>
        <li>Comply with all applicable laws and regulations</li>
        <li>Provide accurate and truthful financial information</li>
        <li>Use the Service only for legitimate business or personal accounting purposes</li>
        <li>Respect the intellectual property rights of others</li>
        <li>Not engage in any activity that could harm, disable, or impair the Service</li>
        <li>Not attempt to gain unauthorized access to any part of the Service</li>
        <li>Not use the Service for any illegal or fraudulent purpose</li>
      </ul>
      <p>
        You acknowledge that you are solely responsible for the accuracy and completeness of the financial data you input into the Service. While our AI technology aims to assist with categorization and processing, you remain responsible for reviewing and verifying all financial information and reports generated by the Service.
      </p>

      <h2>Subscription and Payment Terms</h2>
      <h3>Subscription Plans</h3>
      <p>
        We offer various subscription plans with different features and pricing. The current subscription options and their respective features are described on our pricing page. We reserve the right to change our subscription plans and pricing at any time.
      </p>

      <h3>Payment</h3>
      <p>
        By subscribing to our Service, you agree to pay all fees associated with your selected subscription plan. Payments are charged on a recurring basis (monthly or annually) according to your chosen billing cycle. All payments are non-refundable except as expressly stated in our Refund Policy or as required by applicable law.
      </p>
      <p>
        You authorize us to charge the payment method you provide during registration for all applicable fees. If your payment cannot be completed, we may suspend or terminate your access to the Service.
      </p>

      <h3>Free Trial</h3>
      <p>
        We may offer a free trial period for new users. At the end of the trial period, your account will automatically convert to a paid subscription unless you cancel before the trial ends. You may be required to provide payment information to start a free trial.
      </p>

      <h3>Taxes</h3>
      <p>
        All fees are exclusive of taxes, which may be added to the final payment amount where applicable. You are responsible for paying all taxes associated with your use of the Service.
      </p>

      <h2>Delivery of Service</h2>
      <p>
        Upon successful payment and account creation, you will receive:
      </p>
      <ul>
        <li>Immediate access to the Salient AI Accounting Platform through our web interface</li>
        <li>Access to all features included in your selected subscription plan</li>
        <li>The ability to connect bank accounts, upload receipts, and utilize all available tools</li>
        <li>Regular updates and improvements to the platform at no additional cost</li>
        <li>Customer support via email (all plans) or priority support (higher-tier plans)</li>
      </ul>
      <p>
        For Enterprise customers, additional onboarding assistance and custom implementation services may be provided as specified in your service agreement.
      </p>

      <h2>Intellectual Property Rights</h2>
      <p>
        The Service and its original content, features, and functionality are owned by Himalayas X LLC and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
      </p>
      <p>
        You may not:
      </p>
      <ul>
        <li>Copy, modify, distribute, sell, or lease any part of our Service</li>
        <li>Reverse engineer or attempt to extract the source code of our software</li>
        <li>Remove any copyright, trademark, or other proprietary notices</li>
        <li>Use our trademarks, logos, or other proprietary information without our express written consent</li>
      </ul>
      <p>
        You retain all rights to your data that you upload, input, or create within the Service. By using our Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and process your data solely for the purpose of providing and improving the Service.
      </p>

      <h2>Data Usage and AI Training</h2>
      <p>
        Our Service utilizes artificial intelligence to provide automated accounting features. By using our Service, you understand and agree that:
      </p>
      <ul>
        <li>Your anonymized and aggregated data may be used to train and improve our AI models</li>
        <li>We implement strict privacy and security measures to protect your data during AI processing</li>
        <li>We do not use your identifiable financial data to train AI models without your explicit consent</li>
        <li>You can opt out of certain data usage for AI training through your account settings</li>
      </ul>
      <p>
        For more information on how we handle your data, please refer to our Privacy Policy.
      </p>

      <h2>Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
      </p>
      <p>
        We do not warrant that:
      </p>
      <ul>
        <li>The Service will function uninterrupted, secure, or available at any particular time or location</li>
        <li>Any errors or defects will be corrected</li>
        <li>The Service is free of viruses or other harmful components</li>
        <li>The results of using the Service will meet your requirements</li>
      </ul>
      <p>
        While our AI-powered features are designed to assist with accounting tasks, we do not guarantee the accuracy, completeness, or reliability of any automated categorization, calculation, or prediction. You are responsible for verifying all information processed by our Service.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL HIMALAYAS X LLC, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
      </p>
      <ul>
        <li>Your access to or use of or inability to access or use the Service</li>
        <li>Any conduct or content of any third party on the Service</li>
        <li>Any content obtained from the Service</li>
        <li>Unauthorized access, use, or alteration of your transmissions or content</li>
        <li>Financial decisions made based on information provided by the Service</li>
      </ul>
      <p>
        Our total liability for any claim arising out of or relating to these Terms or our Service shall not exceed the amount paid by you to us during the 12 months preceding the claim.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to defend, indemnify, and hold harmless Himalayas X LLC, its officers, directors, employees, and agents, from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with your access to or use of the Service, your violation of these Terms, or your violation of any third-party rights.
      </p>

      <h2>Termination</h2>
      <p>
        We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including, without limitation, if you breach these Terms.
      </p>
      <p>
        Upon termination:
      </p>
      <ul>
        <li>Your right to use the Service will immediately cease</li>
        <li>You will no longer have access to your account or any data stored within it</li>
        <li>Any outstanding payment obligations will remain in effect</li>
      </ul>
      <p>
        You may request a copy of your data prior to account termination, subject to our data retention policies and applicable laws.
      </p>

      <h2>Modifications to the Service and Terms</h2>
      <p>
        We reserve the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. We shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the Service.
      </p>
      <p>
        We may revise these Terms from time to time. The most current version will always be posted on our website. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised Terms.
      </p>

      <h2>Governing Law and Dispute Resolution</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of law provisions.
      </p>
      <p>
        Any dispute arising from or relating to these Terms or your use of the Service shall be resolved through:
      </p>
      <ol>
        <li>Informal negotiation: We encourage you to contact us first to seek an informal resolution.</li>
        <li>Mediation: If informal negotiation is unsuccessful, the parties agree to mediation in New York, with costs shared equally.</li>
        <li>Arbitration: If mediation is unsuccessful, the dispute will be resolved by binding arbitration in accordance with the rules of the American Arbitration Association.</li>
      </ol>
      <p>
        You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.
      </p>

      <h2>Severability</h2>
      <p>
        If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect.
      </p>

      <h2>Entire Agreement</h2>
      <p>
        These Terms, together with our Privacy Policy and any other legal notices published by us on the Service, constitute the entire agreement between you and Himalayas X LLC regarding your use of the Service.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about these Terms, please contact us at:
      </p>
      <p>
        Himalayas X LLC<br />
        418 Broadway, Ste 5184<br />
        Albany, NY 12207<br />
        Email: legal@himalayasx.com<br />
        Phone: (412) 301-7426
      </p>
    </PolicyLayout>
  )
}
